<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Salvar Alteraes_button cancel</name>
   <tag></tag>
   <elementGuidId>37c55a8d-526e-41ea-b26c-3323ce46690a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.cancel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Cancelar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ad86f5e-cc87-4ea3-82de-3810bf42265b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/localidades/listar</value>
      <webElementGuid>905d5857-098e-4547-a30e-bf9307c0dcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button cancel</value>
      <webElementGuid>abaf066c-99f4-4503-842e-1b615a9dbd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>6fc94638-cb58-4092-b2ea-668a38cf1270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/form[1]/a[@class=&quot;button cancel&quot;]</value>
      <webElementGuid>e8d747fa-84aa-4c45-a347-ff54be986f06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancelar')]</value>
      <webElementGuid>60549b54-ddbb-4cae-a2b8-7a6bfae69e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salvar Alterações'])[1]/following::a[1]</value>
      <webElementGuid>286e6b9e-b977-4221-b3cf-8a506d717e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Câmera'])[1]/following::a[1]</value>
      <webElementGuid>3db356b3-5473-4c3f-bb80-fe86c5ca5393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MottuFlow'])[2]/preceding::a[1]</value>
      <webElementGuid>7a5a3d47-9d07-4183-9496-ab7a452c437f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancelar']/parent::*</value>
      <webElementGuid>efc9e967-3521-4c59-ad3b-fdfa829fed3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/localidades/listar')]</value>
      <webElementGuid>216d8721-8d66-4e69-abf4-6111048a6aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>57b317ac-2da1-4671-8769-7970679020c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/localidades/listar' and (text() = 'Cancelar' or . = 'Cancelar')]</value>
      <webElementGuid>ac07d83a-1dbd-47f6-851f-05bac08909a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
