<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OPERACIONAL_button edit</name>
   <tag></tag>
   <elementGuidId>ab8f252a-76b2-4b55-afa9-aa50f54bf227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Editar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5ec16e8-adec-43ec-b831-3e2f6dc5b605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/localidades/editar/1</value>
      <webElementGuid>75998a65-2238-4d8c-9a8e-c5651e9d18e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button edit</value>
      <webElementGuid>7750f747-8f68-46fd-8c1f-0b732e01e304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>1d36b805-dfc3-4447-a868-b9eb2c98324b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[2]/table[1]/tbody[1]/tr[1]/td[@class=&quot;actions&quot;]/a[@class=&quot;button edit&quot;]</value>
      <webElementGuid>5ff56771-6bf3-4cb4-9f5a-619e053e02f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Editar')]</value>
      <webElementGuid>b424d558-c2c4-4596-b069-7a98b3b2210b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPERACIONAL'])[1]/following::a[1]</value>
      <webElementGuid>42bfda34-63ec-4313-8bea-4173b086061c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patio Central'])[2]/following::a[1]</value>
      <webElementGuid>b523fe7a-4ac5-4b9d-823f-5b3472c387cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deletar'])[1]/preceding::a[1]</value>
      <webElementGuid>4ba97af8-6ef8-4d04-995d-ff44458fa71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saída norte'])[2]/preceding::a[1]</value>
      <webElementGuid>8492d895-9577-4432-b8a6-6f1357dadc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Editar']/parent::*</value>
      <webElementGuid>9daaa522-4f5a-4185-98a5-1ec9751c76c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/localidades/editar/1')]</value>
      <webElementGuid>f4b22b90-6ff0-4b24-85ab-fc201c3f389e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>0725934a-00d4-4d8d-be36-5a3d97823212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/localidades/editar/1' and (text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>0fb99381-bceb-4b03-8768-6553d6d1de80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
