<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dicionrio ArUco_startBtn</name>
   <tag></tag>
   <elementGuidId>77ea7495-5292-48d9-b01c-5a677edd1637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='startBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72a2efa2-ca5a-48a6-8e1c-d8aadf3dbeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startBtn</value>
      <webElementGuid>499e4f41-f65d-4557-8419-b7b39f21f891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>55af5145-5f98-46ca-9ba3-c994fca957c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31bee5af-f104-40da-b65a-0f2917725b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Iniciar câmera
          </value>
      <webElementGuid>20d67757-e97f-45d7-8a6c-75bdef174336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startBtn&quot;)</value>
      <webElementGuid>eec8e0fe-25fe-40d7-b1d1-3acd998d045c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='startBtn']</value>
      <webElementGuid>1662b5e4-3503-49e7-96da-3bb817e567d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dicionário ArUco:'])[1]/following::button[1]</value>
      <webElementGuid>ed2ff8a5-fcf5-4156-a9e6-18378914f879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecione a câmera:'])[1]/following::button[1]</value>
      <webElementGuid>9a09939a-4910-456b-bf69-639aeaedda5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parar câmera'])[1]/preceding::button[1]</value>
      <webElementGuid>e79c2360-569e-4649-a795-69b83b119723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parado'])[1]/preceding::button[2]</value>
      <webElementGuid>8f3b48d2-eedb-4e7a-87c2-960dae42a24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Iniciar câmera']/parent::*</value>
      <webElementGuid>95eb69ae-10de-4651-b128-cde101180297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c410d1a9-2b4f-4427-8f25-7225a5e2734f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'startBtn' and @type = 'button' and (text() = '
            Iniciar câmera
          ' or . = '
            Iniciar câmera
          ')]</value>
      <webElementGuid>82a87fce-e790-4a26-846e-5027306d3d26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
