<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3</name>
   <tag></tag>
   <elementGuidId>3eda6469-aa12-4f06-8b70-f6c74449b6a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(7)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Gerenciar Status')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a85dfc5f-4272-4d1c-8f1e-aeb10fc1970b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/status/listar-cadastrar-delete</value>
      <webElementGuid>3b3de665-667c-4540-86f2-189acfdbd88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gerenciar Status</value>
      <webElementGuid>b750f485-d4dd-456e-a081-fcd36ed76a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;main-right&quot;]/a[7]</value>
      <webElementGuid>f7ac0bfb-d906-45c0-9174-aaad64eb08ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gerenciar Status')]</value>
      <webElementGuid>fd0edcca-3150-47e4-8d87-c880a3b6ee93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerenciar Localidade'])[1]/following::a[1]</value>
      <webElementGuid>83a7547c-8cc8-4ab3-b529-2246682693a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerenciar Camera'])[1]/following::a[2]</value>
      <webElementGuid>b4e46b70-8ce6-46ea-8acf-8c4545eccb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abrir Câmera (IoT)'])[1]/preceding::a[1]</value>
      <webElementGuid>28f4a508-4034-43ad-9685-c232ff9d6730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MottuFlow'])[2]/preceding::a[2]</value>
      <webElementGuid>7a64d078-3ab2-4769-b79e-cd2f326c3581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gerenciar Status']/parent::*</value>
      <webElementGuid>1aeb4137-31b8-4190-a1b6-ad0d17ed55d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/status/listar-cadastrar-delete')]</value>
      <webElementGuid>d16253f4-8c00-4fab-b881-eae87a62622d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]</value>
      <webElementGuid>a6baf499-94d3-431a-8fd9-36b1bdc925f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/status/listar-cadastrar-delete' and (text() = 'Gerenciar Status' or . = 'Gerenciar Status')]</value>
      <webElementGuid>bc9bec1f-ac23-4a8a-a160-516fae3f771e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
