<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>fc3c8e93-1051-48f1-a842-7f4776ad5d6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Gerenciar Localidade')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08c864a2-c1da-41f1-aeac-b9a6cbedc4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/localidades/listar-cadastrar-delete</value>
      <webElementGuid>42d3071f-ac72-4fcc-9f0d-9849ad16c6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gerenciar Localidade</value>
      <webElementGuid>0d293a85-1380-465f-8fb7-5d5fa936347b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;main-right&quot;]/a[6]</value>
      <webElementGuid>41189e9a-f0a1-44d0-9574-0384c427789f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gerenciar Localidade')]</value>
      <webElementGuid>6938a3fe-0933-43bd-8e74-6fc7059054c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerenciar Camera'])[1]/following::a[1]</value>
      <webElementGuid>65956755-caf7-41e0-8073-dca29ea2c957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerenciar ArUco Tag'])[1]/following::a[2]</value>
      <webElementGuid>0907d208-bd60-4cdb-864c-7f062752deca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerenciar Status'])[1]/preceding::a[1]</value>
      <webElementGuid>26e60a46-9238-4ea8-8221-692de90ca516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abrir Câmera (IoT)'])[1]/preceding::a[2]</value>
      <webElementGuid>37ab7de4-6468-42a9-9735-e9e2a54af4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gerenciar Localidade']/parent::*</value>
      <webElementGuid>6d537788-8f57-4c12-a5d2-43155a41d981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/localidades/listar-cadastrar-delete')]</value>
      <webElementGuid>72e49ac8-a1c3-4df1-8e70-6634daecb9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>7379c3be-bb9a-4b18-afb0-95723bb68beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/localidades/listar-cadastrar-delete' and (text() = 'Gerenciar Localidade' or . = 'Gerenciar Localidade')]</value>
      <webElementGuid>a14b1be9-885a-450b-bdfd-b18e3550ec1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
